### ISSUE TITLE
Make ImGui work

### ISSUE THREAD

**Issue by gardzielb** [gardzielb/EngineerToBeDx12#1]
I put ImGui in the project and tried to add the code from their DX12 example (ImGui repo, docking branch), but there are problems with conflicting pipeline state when rendering ImGui. I think it has something to do with effect that is applied to draw triangle (Game.cpp, line 153), but the example ImGui code does not use anything like that.
All code that I added to the project which is associated with ImGui is marked with comments:
// IMGUI
// ------------------------------
... code ...
// ------------------------------
There are such fragments in Game.h, Game.cpp, DeviceResources.h and DeviceResources.cpp

**Comment by jankupis** [comment]
The error says (emphasis is mine):

> D3D12 ERROR: ID3D12CommandList::DrawIndexedInstanced: The render target format in slot 0 does not match that specified by the current pipeline state. (pipeline state = **R8G8B8A8_UNORM**, render target format = **B8G8R8A8_UNORM**, RTV ID3D12Resource* = 0x0000026A4C498250:'Render target 1') [ EXECUTION ERROR #613: RENDER_TARGET_FORMAT_MISMATCH_PIPELINE_STATE]

We can changed that on L84 here:
https://github.com/gardzielb/EngineerToBeDx12/blob/dc65e1b028b044cfda75c57354cbf51a7166c1ec/EngineerToBeDx12DR/Game.cpp#L82-L87

This generates another error, but seems to move us forward

**Comment by jankupis** [comment]
After matching the pipline state we are met with this probem:

> D3D12 ERROR: ID3D12CommandQueue::ExecuteCommandList: The command allocator was reset after the command list was recorded. [ EXECUTION ERROR #541: COMMAND_ALLOCATOR_RESET]

This seems to be a synchronization issue, as stepping through the code manually doesn't generate this error

**Comment by jankupis** [comment]
I think I have a WIP fix

Pros:
The app doesn't crash and ImGui is displayed

Cons:
ImGui windows within the application window don't respond to clicks
The triangle is no longer drawn
